export const qk = {
  projects: (filters?: Record<string, unknown>) =>
    ["projects", filters ?? {}] as const,
  project: (id: number) => ["projects", id] as const,
  tags: ["tags"] as const,
  projectTags: (projectId: number) => ["project-tags", projectId] as const,
  notes: (projectId: number) => ["notes", projectId] as const,
  tasks: (filter: string) => ["tasks", filter] as const,
  relationships: (projectId: number) => ["relationships", projectId] as const,
  links: (projectId: number) => ["links", projectId] as const,
  commands: (projectId: number) => ["commands", projectId] as const,
  projectTasks: (projectId: number) => ["project-tasks", projectId] as const,
  templates: ["templates"] as const,
  screenshots: (projectId: number) => ["screenshots", projectId] as const,
  readme: (projectId: number) => ["readme", projectId] as const,
  heatmap: ["activity-heatmap"] as const,
  analytics: ["analytics"] as const,
  graph: ["graph"] as const,
  overviewMermaid: ["mermaid-overview"] as const,
};
